---
- name: Install latest mlocate and update locate database
  apt: >
    upgrade=yes
    update_cache=yes
    cache_valid_time=3600  

- name: install mlocate 
  package: name={{item}} state=latest
  with_items:
    - mlocate

- name: Update locate database
  command: updatedb